OrderManagmentSystem/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using OrderManagmentSytemBAL.CustomerRepositry;
using OrderManagmentSytemDAL.ViewModels;
using Microsoft.AspNetCore.Http.Features;
using AspNetCoreHero.ToastNotification.Abstractions;
namespace OrderManagmentSystem.Controllers
{
    public class CustomerController : Controller

    {
        private readonly ICustomerRepositry customerRepositry;
        private readonly INotyfService notyf;

        public CustomerController(ICustomerRepositry customerRepositry,INotyfService notyfService)
        {
            this.customerRepositry = customerRepositry;
            this.notyf = notyfService;
        }

        [HttpGet]
        [Route("/Customers")]
        public IActionResult CustomerList()
        {
            Response customerDetails = customerRepositry.SearchCustomerSP(new CustomerDetails());
            return View(customerDetails);
        }
        [HttpGet]
        [Route("/Customers/edit")]
        public IActionResult EditCustomer(int customerId)
        {
            CustomerDetails customer = new CustomerDetails
            {
                CustomerId = customerId,
            };
            Response customerDetailsResponse = customerRepositry.SearchCustomerSP(customer);
            if (customerDetailsResponse.IsSuccess && customerDetailsResponse.Result is IEnumerable<CustomerDetails> customers && customers.Count() == 1)
            {
                return View("CustomerForm", customers.First());
            }
            notyf.Error("Customer not Found");
            return RedirectToAction("CustomerList");
        }
        [HttpPost]
        [Route("/Customers/deleteconfirmation")]
        public IActionResult DeleteConfirmationCustomer(List<int> customerIds)
        {
            Response searchCustomer = customerRepositry.CustomersExits(customerIds);
            if (searchCustomer.IsSuccess)
            {
                return PartialView("ConfirmationBox", customerIds);
            }
            notyf.Error("Customer not Found");
            return Json(new { message = "Customer Not Exits" });
        }

        [HttpPost]
        [Route("/Customers/delete")]
        public IActionResult DeleteCustomer(List<int> customerIds)
        {
            Response searchCustomer = customerRepositry.CustomersExits(customerIds);
            if (searchCustomer.IsSuccess)
            {
                Response customerDetails = customerRepositry.DeleteCustomers(customerIds);
                if (customerDetails.IsSuccess)
                {
                    notyf.Success("Customer Deleted Successfully.");
                    return RedirectToAction("CustomerList");
                }
               
            }
            notyf.Error("Customer not Found");
            return RedirectToAction("CustomerList");
        }
        [HttpGet]
        [Route("/Customers/Addcustomer")]
        public IActionResult CreateCustomer()
        {
            CustomerDetails customer = new CustomerDetails();
            return View("CustomerForm", customer);

        }
        [HttpPost]
        [Route("/Customers/Addcustomer")]
        public IActionResult CreateCustomer(CustomerDetails customerDetails, IFormFile? ProfilePhoto)
        {
            if(customerDetails.CustomerId!=0 && !customerRepositry.CustomersExits(new List<int>(customerDetails.CustomerId)).IsSuccess)
            {
                notyf.Error("Customer not Found");
                return RedirectToAction("CustomerList");
            }
            if (!ModelState.IsValid)
            {
                return View("CustomerForm", customerDetails);
            }
            Response customerCheck = customerRepositry.CustomerExits(customerDetails.CustomerId, customerDetails.EmailId, customerDetails.PhoneNumber);
            if (customerCheck.IsSuccess)
            {
                ModelState.AddModelError("CustomerId", "Customer with this email or phone number already exists.");
                return View("CustomerForm", customerDetails);
            }
            if (!(ProfilePhoto == null || !(ProfilePhoto.Length > 0)))
            {
                string[] _permittedExtensions = { ".jpg", ".jpeg", ".png" };
                string[] _permittedMimeTypes = { "image/jpeg", "image/png" };
                var fileExtension = System.IO.Path.GetExtension(ProfilePhoto.FileName).ToLowerInvariant();
                var fileContentType = ProfilePhoto.ContentType.ToLowerInvariant();

                if (!_permittedExtensions.Contains(fileExtension) || !_permittedMimeTypes.Contains(fileContentType))
                {
                    ModelState.AddModelError("Photo", "only png and jpg  format file upload.");
                    return View("CustomerForm", customerDetails);
                }
                string fileName = customerRepositry.UploadFile(ProfilePhoto);
                if (fileName == null && customerDetails.CustomerId == 0)
                {
                    ModelState.AddModelError("Photo", "Error in Uploading File.");
                    return View("CustomerForm", customerDetails);
                }
                customerDetails.Photo = fileName;
            }
            Response response = customerRepositry.SaveCustomersSP(customerDetails, false);
            if (response.IsSuccess)
            {
                if (customerDetails.CustomerId == 0)
                {
                    notyf.Success("Customer Add Successfully.");
                }
                else
                {
                    notyf.Success("Edit Customer Successfully.");
                }
                return RedirectToAction("CustomerList");
            }
            if (customerDetails.CustomerId == 0)
            {
                notyf.Error("Customer not Added");
            }
            else
            {
                notyf.Error("Customer not Edited");
            }
            return View("CustomerForm", customerDetails);
        }



    }
}

OrderManagmentSystem/Controllers/OrderController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using OrderManagmentSytemBAL.CustomerRepositry;
using OrderManagmentSytemBAL.OrderRepositry;
using OrderManagmentSytemDAL.ViewModels;

namespace OrderManagmentSystem.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepositry orderRepositry;
        private readonly ICustomerRepositry customerRepositry;
        private readonly INotyfService notyf;

        public OrderController(IOrderRepositry orderRepositry, ICustomerRepositry customerRepositry, INotyfService notyfService)
        {
            this.orderRepositry = orderRepositry;
            this.customerRepositry = customerRepositry;
            this.notyf = notyfService;
        }
        [HttpGet]
        [Route("/Orders")]
        public IActionResult OrderList()
        {
            Response response = orderRepositry.SearchOrderSP(new Order());
            return View(response);
        }


        [HttpGet]
        [Route("/Orders/Addorder")]
        public IActionResult CreateOrder()
        {
            Response customersResponse = customerRepositry.SearchCustomerSP(new CustomerDetails());
            CreateOrder createOrder = new CreateOrder();
            createOrder.CustomerDetails = customersResponse.Result as IEnumerable<CustomerDetails>;
            createOrder.Order = new Order();
            createOrder.Order.CustomerId = -1;
            return View("OrderForm", createOrder);
        }

        [HttpPost]
        [Route("/Orders/Addorder")]
        public IActionResult CreateOrder(Order order)
        {

            if (order.OrderId != 0 && !orderRepositry.OrdersExits(new List<int>(order.OrderId)).IsSuccess)
            {
                notyf.Error("Order not Found");
                return RedirectToAction("OrderList");
            }
            if (!ModelState.IsValid)
            {
                Response customersResponse = customerRepositry.SearchCustomerSP(new CustomerDetails());
                IEnumerable<CustomerDetails> customerDetails = customersResponse.Result as IEnumerable<CustomerDetails>;
                CreateOrder createOrder = new CreateOrder
                {
                    CustomerDetails = customerDetails,
                    Order = order
                };

                return View("OrderForm", createOrder);
            }

            Response response = orderRepositry.SaveOrdersSP(order, false);

            if (response.IsSuccess)
            {
                if (order.OrderId == 0)
                {
                    notyf.Success("Order Add Successfully.");
                }
                else
                {
                    notyf.Success("Edit Order Successfully.");
                }
                return RedirectToAction("OrderList");
            }
            else
            {
                Response customersResponse = customerRepositry.SearchCustomerSP(new CustomerDetails());
                CreateOrder createOrder = new CreateOrder
                {
                    CustomerDetails = customersResponse.Result as IEnumerable<CustomerDetails>,
                    Order = order
                };
                if (order.OrderId == 0)
                {
                    notyf.Error("Order not Added");
                }
                else
                {
                    notyf.Error("Order not Edited");
                }
                return View("OrderForm", createOrder);
            }
        }
        [HttpGet]
        [Route("/Orders/edit")]
        public IActionResult EditOrder(int orderId)
        {
            Response customersResponse = customerRepositry.SearchCustomerSP(new CustomerDetails());
            IEnumerable<CustomerDetails> customerDetails = customersResponse.Result as IEnumerable<CustomerDetails>;


            Order searchOrder = new Order
            {
                OrderId = orderId
            };
            Response orderResponse = orderRepositry.SearchOrderSP(searchOrder);
            if (orderResponse.IsSuccess && orderResponse.Result is IEnumerable<OrderWithCustomer> orders && orders.Count() == 1)
            {
                CreateOrder viewModel = new CreateOrder
                {
                    CustomerDetails = customerDetails,
                    Order = new Order
                    {
                        OrderId = orders.First().OrderId,
                        ProductName = orders.First().ProductName,
                        Quantity = orders.First().Quantity,
                        Amount = orders.First().Amount,
                        CustomerId = orders.First().CustomerId,
                    },
                };
                return View("OrderForm", viewModel);
            }
            notyf.Error("Order not Found");
            return RedirectToAction("OrderList");
        }
        [HttpPost]
        [Route("/Orders/deleteconfirmation")]
        public IActionResult DeleteConfirmationOrder(List<int> orderIds)
        {
            Response order = orderRepositry.OrdersExits(orderIds);

            if (order.IsSuccess)
            {
                return PartialView("ConfirmationBox", orderIds);
            }
            notyf.Error("Order not Found");
            return Json(new { message = "Order Not Exits" });
        }

        [HttpPost]
        [Route("/Orders/delete")]
        public IActionResult DeleteOrder(List<int> orderIds)
        {
            Response orders = orderRepositry.OrdersExits(orderIds);

            if (orders.IsSuccess)
            {
                Response DeleteOrders = orderRepositry.DeleteOrders(orderIds);
                if (DeleteOrders.IsSuccess)
                {
                    notyf.Success("Order deleted successfully");
                }
                else
                {
                    notyf.Error("Order not Deleted");
                }
                return RedirectToAction("OrderList");
            }
            notyf.Error("Order not Found");
            return RedirectToAction("OrderList");
        }


        [HttpGet]
        [Route("/customerorders")]
        public IActionResult CustomersOrder()
        {
            Response response = orderRepositry.CustomerOrderDetails();
            IEnumerable<CustomersOrderDetails> customersOrderDetails = response.Result as IEnumerable<CustomersOrderDetails>;
            return View(response);
        }
    }
}

OrderManagmentSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrderManagmentSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script> *@

   
    <link rel="stylesheet" href="~/OrderManagmentSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OrderManagmentSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a asp-action="CustomerList" asp-controller="Customer" type="button" class="nav-link text-dark">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="OrderList" asp-controller="Order" type="button" class="nav-link text-dark">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Order" asp-action="CustomersOrder">Customers Order Detail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container my-5">
        <main role="main" class="pb-3 mx-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white" style="z-index:5000px;">
        <div class="container">
            &copy; 2024 - OrderManagmentSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>